name: 'request-labeler'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
