name: 'check-branches'
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: hello
        with:
          milliseconds: 5000
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
