name: 'check-branches'
on:
  pull_request_target

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - uses: ./
        id: hello
        with:
          milliseconds: 5000
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
