name: 'report-to-main'
on:
  pull_request:
    branches: 
      - 'prod*'
    types: [synchronize, opened, reopened, edited, closed]

jobs:
  tag-for-report:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: AlexisJacob1/cherry-picker@v0.1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
