name: 'build-test'
on: # rebuild any PRs and main branch changes
  - pull_request_target
  # push:
  #   branches:
  #     - main
  #     - 'releases/*'

jobs:
  # build: # make sure build/ci work properly
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm install
  #     - run: |
  #         npm run build
  #     - run: |
  #         npm run package
  build: # make sure the action works on a clean machine without building
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build
      - run: |
          npm run package
      - uses: ./
        with:
          milliseconds: 1000
